---

packages:
  - apache2
  - ceilometer-agent-central
  - ceilometer-agent-notification
  - ceilometer-polling
  - ceph
  - ceph-deploy
  - cinder-api
  - cinder-backup
  - cinder-scheduler
  - cinder-volume
  - curl
  - etcd
  - fail2ban
  - glance
  - haproxy
  - libapache2-mod-wsgi
  - magnum-api
  - magnum-conductor
  - mariadb-server
  - memcached
  - neutron-dhcp-agent
  - neutron-l3-agent
  - neutron-linuxbridge-agent
  - neutron-metadata-agent
  - neutron-plugin-ml2
  - neutron-server
  - nova-api
  - nova-conductor
  - nova-novncproxy
  - nova-placement-api  
  - nova-scheduler
  - openstack-dashboard
  - phpmyadmin
  - python-gnocchiclient
  - python-magnumclient
  - python-memcache
  - python-pymysql
  - rabbitmq-server
  - redis
  - heat-api
  - heat-api-cfn
  - heat-engine
  - gettext
#  - python3-heat-dashboard
#  - python3-neutron-fwaas-dashboard
#  - python3-neutron-lbaas-dashboard
#  - python3-octavia-dashboard
#  - python3-trove-dashboard


  # - nova-spiceproxy
  # - spice-html5

# https://docs.openstack.org/heat-dashboard/latest/install/index.html
# cp /usr/lib/python3/dist-packages/heat_dashboard/enabled/_[1-9]*.py /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/
# root@os-lab-control:/usr/share/openstack-dashboard# DJANGO_SETTINGS_MODULE=openstack_dashboard.settings python3 manage.py compress --force


mysql_databases:
  - keystone
  - glance
  - nova
  - nova_api
  - nova_cell0
  - placement
  - neutron
  - gnocchi
  - cinder
  - magnum
  - heat


keystone_domains:
  example: "An Example Domain"
  magnum: "Owns users and projects created by magnum" 
  heat: "Stack projects and users" 

keystone_projects:
  service: "Service Project"
  myproject: "Demo Project"

keystone_users:
  demo:
    pass: '{{DEMO_PASS}}'
    project: myproject
    role: member
  # demo:
  #   pass: '{{DEMO_PASS}}'
  #   project: myproject
  #   role: heat_stack_owner
  myuser:
    pass: '{{MYUSER_PASS}}'
    project: myproject
    role: myrole
  glance:
    pass: '{{GLANCE_PASS}}'
    project: service
    role: admin
  nova:
    pass: '{{NOVA_PASS}}'
    project: service
    role: admin
  placement:
    pass: '{{PLACEMENT_PASS}}'
    project: service
    role: admin
  neutron:
    pass: '{{NEUTRON_PASS}}'
    project: service
    role: admin
  cinder:
    pass: '{{CINDER_PASS}}'
    project: service
    role: admin
  ceilometer:
    pass: '{{ CEILOMETER_PASS }}'
    project: service
    role: admin
  gnocchi:
    pass: '{{GNOCCHI_PASS}}'
    project: service
    role: admin
  magnum:
    pass: '{{MAGNUM_PASS}}'
    project: service
    role: admin
  heat:
    pass: '{{HEAT_PASS}}'
    project: service
    role: admin

keystone_domain_users:
  magnum_domain_admin:
    pass: '{{MAGNUM_PASS}}'
    role: admin
    domain: "{{ MAGNUM_DOMAIN_ID | default('magnum')}}"
  heat_domain_admin:
    pass: '{{HEAT_PASS}}'
    role: admin
    domain: "{{ HEAT_DOMAIN_ID | default('heat')}}"

keystone_roles:
  - myrole
  - heat_stack_owner
  - heat_stack_user
  - heat_stack_owner


keystone_services:
  glance:
    type: image
    description: "OpenStack Image"
  nova:
    type: compute
    description: "OpenStack Compute"
  placement:
    type: placement
    description: "Placement API"
  neutron:
    type: network
    description: "OpenStack Networking" 
  gnocchi:
    type: metric
    description: "Metric Service" 
  cinderv2:
    type: volumev2
    description: "OpenStack Block Storage" 
  cinderv3:
    type: volumev3
    description: "OpenStack Block Storage" 
  magnum:
    type: container-infra
    description: "OpenStack Container Infrastructure Management Service" 
  heat:
    type: orchestration
    description: "Orchestration" 
  heat-cfn:
    type: cloudformation
    description: "Orchestration" 


keystone_endpoints:
  - region: RegionOne
    service: glance
    interface: public 
    url: http://{{control_node_ip_remote}}:9292
  - region: RegionOne
    service: glance
    interface: internal 
    url: http://os-lab-control:9292
  - region: RegionOne
    service: glance
    interface: admin 
    url: http://os-lab-control:9292

  - region: RegionOne
    service: nova
    interface: public 
    url: http://{{control_node_ip_remote}}:8774/v2.1
  - region: RegionOne
    service: nova
    interface: internal 
    url: http://os-lab-control:8774/v2.1
  - region: RegionOne
    service: nova
    interface: admin 
    url: http://os-lab-control:8774/v2.1

  - region: RegionOne
    service: placement
    interface: public 
    url: http://{{control_node_ip_remote}}:8778
  - region: RegionOne
    service: placement
    interface: internal 
    url: http://os-lab-control:8778
  - region: RegionOne
    service: placement
    interface: admin 
    url: http://os-lab-control:8778

  - region: RegionOne
    service: neutron
    interface: public 
    url: http://{{control_node_ip_remote}}:9696
  - region: RegionOne
    service: neutron
    interface: internal 
    url: http://os-lab-control:9696
  - region: RegionOne
    service: neutron
    interface: admin 
    url: http://os-lab-control:9696

  - region: RegionOne
    service: gnocchi
    interface: public 
    url: http://{{control_node_ip_remote}}:8041
  - region: RegionOne
    service: gnocchi
    interface: internal 
    url: http://os-lab-control:8041
  - region: RegionOne
    service: gnocchi
    interface: admin 
    url: http://os-lab-control:8041

  - region: RegionOne
    service: cinderv2
    interface: public 
    url: http://{{control_node_ip_remote}}:8776//v2/$(project_id)s
  - region: RegionOne
    service: cinderv2
    interface: internal 
    url: http://os-lab-control:8776/v2/$(project_id)s
  - region: RegionOne
    service: cinderv2
    interface: admin 
    url: http://os-lab-control:8776/v2/$(project_id)s

  - region: RegionOne
    service: cinderv3
    interface: public 
    url: http://{{control_node_ip_remote}}:8776/v3/$(project_id)s
  - region: RegionOne
    service: cinderv3
    interface: internal 
    url: http://os-lab-control:8776/v3/$(project_id)s
  - region: RegionOne
    service: cinderv3
    interface: admin 
    url: http://os-lab-control:8776/v3/$(project_id)s

  - region: RegionOne
    service: magnum
    interface: public 
    url: http://{{control_node_ip_remote}}:9511/v1
  - region: RegionOne
    service: magnum
    interface: internal 
    url: http://os-lab-control:9511/v1
  - region: RegionOne
    service: magnum
    interface: admin 
    url: http://os-lab-control:9511/v1

  - region: RegionOne
    service: heat
    interface: public 
    url: http://{{control_node_ip_remote}}:8004/v1/%(tenant_id)s
  - region: RegionOne
    service: heat
    interface: internal 
    url: http://os-lab-control:8004/v1/%(tenant_id)s
  - region: RegionOne
    service: heat
    interface: admin 
    url: http://os-lab-control:8004/v1/%(tenant_id)s

  - region: RegionOne
    service: heat-cfn
    interface: public 
    url: http://{{control_node_ip_remote}}:8000/v1
  - region: RegionOne
    service: heat-cfn
    interface: internal 
    url: http://os-lab-control:8000/v1
  - region: RegionOne
    service: heat-cfn
    interface: admin 
    url: http://os-lab-control:8000/v1
