---

packages:
  - apache2
  - ceilometer-agent-central
  - ceilometer-agent-notification
  - ceilometer-polling
  - ceph
  - ceph-deploy
  - cinder-api
  - cinder-backup
  - cinder-scheduler
  - cinder-volume
  - curl
  - etcd
  - fail2ban
  - glance
  - haproxy
  - libapache2-mod-wsgi
  - mariadb-server
  - memcached
  - neutron-dhcp-agent
  - neutron-l3-agent
  - neutron-linuxbridge-agent
  - neutron-metadata-agent
  - neutron-plugin-ml2
  - neutron-server
  - nova-api
  - nova-conductor
  - nova-novncproxy
  - nova-placement-api  
  - nova-scheduler
  - openstack-dashboard
  - phpmyadmin
  - python-gnocchiclient
  - python-memcache
  - python-pymysql
  - rabbitmq-server
  - redis


  # - nova-spiceproxy
  # - spice-html5


mysql_databases:
  - keystone
  - glance
  - nova
  - nova_api
  - nova_cell0
  - placement
  - neutron
  - gnocchi
  - cinder


keystone_domains:
  example: "An Example Domain"


keystone_projects:
  service: "Service Project"
  myproject: "Demo Project"


keystone_roles:
  - myrole


keystone_services:
  glance:
    type: image
    description: "OpenStack Image"
  nova:
    type: compute
    description: "OpenStack Compute"
  placement:
    type: placement
    description: "Placement API"
  neutron:
    type: network
    description: "OpenStack Networking" 
  gnocchi:
    type: metric
    description: "Metric Service" 
  cinderv2:
    type: volumev2
    description: "OpenStack Block Storage" 
  cinderv3:
    type: volumev3
    description: "OpenStack Block Storage" 


keystone_endpoints:
  - region: RegionOne
    service: glance
    interface: public 
    url: http://{{control_node_ip_remote}}:9292
  - region: RegionOne
    service: glance
    interface: internal 
    url: http://os-lab-control:9292
  - region: RegionOne
    service: glance
    interface: admin 
    url: http://os-lab-control:9292

  - region: RegionOne
    service: nova
    interface: public 
    url: http://{{control_node_ip_remote}}:8774/v2.1
  - region: RegionOne
    service: nova
    interface: internal 
    url: http://os-lab-control:8774/v2.1
  - region: RegionOne
    service: nova
    interface: admin 
    url: http://os-lab-control:8774/v2.1

  - region: RegionOne
    service: placement
    interface: public 
    url: http://{{control_node_ip_remote}}:8778
  - region: RegionOne
    service: placement
    interface: internal 
    url: http://os-lab-control:8778
  - region: RegionOne
    service: placement
    interface: admin 
    url: http://os-lab-control:8778

  - region: RegionOne
    service: neutron
    interface: public 
    url: http://{{control_node_ip_remote}}:9696
  - region: RegionOne
    service: neutron
    interface: internal 
    url: http://os-lab-control:9696
  - region: RegionOne
    service: neutron
    interface: admin 
    url: http://os-lab-control:9696

  - region: RegionOne
    service: gnocchi
    interface: public 
    url: http://{{control_node_ip_remote}}:8041
  - region: RegionOne
    service: gnocchi
    interface: internal 
    url: http://os-lab-control:8041
  - region: RegionOne
    service: gnocchi
    interface: admin 
    url: http://os-lab-control:8041

  - region: RegionOne
    service: cinderv2
    interface: public 
    url: http://{{control_node_ip_remote}}:8776//v2/$(project_id)s
  - region: RegionOne
    service: cinderv2
    interface: internal 
    url: http://os-lab-control:8776/v2/$(project_id)s
  - region: RegionOne
    service: cinderv2
    interface: admin 
    url: http://os-lab-control:8776/v2/$(project_id)s

  - region: RegionOne
    service: cinderv3
    interface: public 
    url: http://{{control_node_ip_remote}}:8776/v3/$(project_id)s
  - region: RegionOne
    service: cinderv3
    interface: internal 
    url: http://os-lab-control:8776/v3/$(project_id)s
  - region: RegionOne
    service: cinderv3
    interface: admin 
    url: http://os-lab-control:8776/v3/$(project_id)s

keystone_users:
  demo:
    pass: '{{DEMO_PASS}}'
    project: myproject
    role: member
  myuser:
    pass: '{{MYUSER_PASS}}'
    project: myproject
    role: myrole
  glance:
    pass: '{{GLANCE_PASS}}'
    project: service
    role: admin
  nova:
    pass: '{{NOVA_PASS}}'
    project: service
    role: admin
  placement:
    pass: '{{PLACEMENT_PASS}}'
    project: service
    role: admin
  neutron:
    pass: '{{NEUTRON_PASS}}'
    project: service
    role: admin
  cinder:
    pass: '{{CINDER_PASS}}'
    project: service
    role: admin
  ceilometer:
    pass: '{{ CEILOMETER_PASS }}'
    project: service
    role: admin
  gnocchi:
    pass: '{{GNOCCHI_PASS}}'
    project: service
    role: admin
