---

control_node_name: "{{ hostvars[groups['control'][0]].ansible_hostname }}"
#control_node_ip: "{{ hostvars[groups['fip_control'][0]]['ansible_eth0']['ipv4']['address'] }}"
control_node_ip: "{{ hostvars[groups['control'][0]]['ansible_default_ipv4']['address'] }}"
control_node_ip_remote: "{{ hostvars[groups['fip_control'][0]]['groups']['fip_control'][0] }}"

ooo:
  compute_api_version: 3
  auth:
    auth_url: http://{{control_node_ip_remote}}:5000/v3
    project_name: admin
    username: admin
    password: "{{ADMIN_PASS}}"
    user_domain_name: default
    project_domain_name: default
  region_name: RegionOne

openstack_repo: deb http://ubuntu-cloud.archive.canonical.com/ubuntu bionic-updates/rocky main
openstack_apt_key: 5EDB1B62EC4926EA
ceph_repo: deb https://download.ceph.com/debian-mimic/ bionic main 
ceph_fsid: 99ff2aa1-9748-4e4b-acfe-d4974f12a3c4

packages:
  - software-properties-common