---

ansible_sudo_pass: "{{ my_sudo_pass }}"
#control_node_name: "os-lab-control"
control_node_name: "{{ hostvars[groups['control'][0]].ansible_hostname }}"
control_node_ip: "{{ hostvars[groups['fip_control'][0]]['ansible_eth0']['ipv4']['address'] }}"
control_node_ip_remote: "{{ hostvars[groups['fip_control'][0]]['groups']['fip_control'][0] }}"

ooo:
  compute_api_version: 3
  auth:
    auth_url: http://{{control_node_ip_remote}}:5000/v3
    project_name: admin
    username: admin
    password: "{{ADMIN_PASS}}"
    user_domain_name: default
    project_domain_name: default
  region_name: RegionOne